<div style="clear:both; height: 40px"></div>
<div id="footer">
  <div style="width:960px; margin: auto; padding-bottom: 30px;">
    <div class="one-fourth">
      <h3>Members in charge</h3>
      <ul style="font-family: Georgia, 'Times New Roman'; margin: 0 15px 0 0">
        <li style="border-bottom: 1px dotted #737a84; border-top: 1px dotted #737a84; padding: 3px 20px; letter-spacing: 2px">Lulu</li>
        <li style="border-bottom: 1px dotted #737a84; padding: 3px 20px; letter-spacing: 2px">Huy Pham</li>
        <li style="border-bottom: 1px dotted #737a84; padding: 3px 20px; letter-spacing: 2px">Minh Nguyen</li>
        <li style="border-bottom: 1px dotted #737a84; padding: 3px 20px; letter-spacing: 2px">Minh Pham</li>
      </ul>
    </div>
    <div class="one-fourth">
      <h3>Headquarter Building</h3>
      <ul style="font-family: Georgia, 'Times New Roman'; margin: 0 15px 0 0">
        <li style="border-bottom: 1px dotted #737a84; border-top: 1px dotted #737a84; padding: 3px 20px; letter-spacing: 2px">Building I, 11th floor</li>
        <li style="border-bottom: 1px dotted #737a84; padding: 3px 20px; letter-spacing: 2px">University of Science</li>
        <li style="border-bottom: 1px dotted #737a84; padding: 3px 20px; letter-spacing: 2px">225 Nguyen Van Cu St., District 5</li>
        <li style="border-bottom: 1px dotted #737a84; padding: 3px 20px; letter-spacing: 2px">Ho Chi Minh city, Vietnam</li>
      </ul>
    </div>
    <div class="one-fourth">
      <h3>Have a nice day</h3>
      Hope we brought you a beautiful memory today!
      <div id="social_icons"> Theme by <a href="http://www.csstemplateheaven.com">CssTemplateHeaven</a><br>
        Photos © <a href="http://dieterschneider.net">Dieter Schneider</a> </div>
    </div>
    <div class="one-fourth last">
      <h3>Socialize</h3>
      <img src="img/icon_fb.png" alt=""> <img src="img/icon_twitter.png" alt=""> <img src="img/icon_in.png" alt=""> </div>
    <div style="clear:both"></div>
  </div>
</div>
<div id="shadow"></div>
<!--
    <!jQuery >
    <script src="js/jquery/jquery.min.js"></script>

    <! Bootstrap Core JavaScript >
    <script src="js/bootstrap/js/bootstrap.min.js"></script>

    <! Metis Menu Plugin JavaScript >
    <script src="js/metisMenu/metisMenu.min.js"></script>

    <! Custom Theme JavaScript >
    <script src="js/sbadmin/sb-admin-2.js"></script>
-->
</body>
</html>
